# Generated by Django 4.0 on 2022-01-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('ide', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=5000)),
            ],
        ),
    ]
