# Generated by Django 4.0 on 2022-01-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
