# Generated by Django 4.0 on 2022-01-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploads_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='username',
            new_name='usernme1',
        ),
    ]
