# Generated by Django 4.0 on 2022-01-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_username_uploads_usernme1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='usernme1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
